import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { generateInsight, getInsights } from '../api/client';
import Markdown from './Markdown';
import Spinner from './Spinner';
import { formatDate } from '../utils/format';
import type { PipelineStatus } from '../types';

interface Props {
  pipelineId: string;
  pipelineStatus: PipelineStatus;
}

/**
 * AI advisor panel for a pipeline run. Shows the latest Claude-generated
 * feedback report, polls while one is being generated, and lets the user
 * request a new analysis on demand.
 */
export default function AIInsights({ pipelineId, pipelineStatus }: Props) {
  const queryClient = useQueryClient();

  const { data: insights, isLoading } = useQuery({
    queryKey: ['insights', pipelineId],
    queryFn: () => getInsights(pipelineId),
    // Poll while an analysis is in flight
    refetchInterval: (query) => {
      const items = query.state.data;
      const busy = items?.some((i) => i.status === 'pending' || i.status === 'generating');
      return busy ? 5_000 : false;
    },
  });

  const generateMutation = useMutation({
    mutationFn: () => generateInsight(pipelineId),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['insights', pipelineId] }),
  });

  const latest = insights?.[0];
  const busy = latest?.status === 'pending' || latest?.status === 'generating';
  const pipelineFinished = pipelineStatus === 'success' || pipelineStatus === 'failed';

  return (
    <section>
      <div className="mb-4 flex items-center justify-between">
        <h3 className="flex items-center gap-2 text-sm font-semibold uppercase tracking-wider text-slate-400">
          <SparklesIcon />
          AI Training Advisor
        </h3>
        {pipelineFinished && (
          <button
            onClick={() => generateMutation.mutate()}
            disabled={busy || generateMutation.isPending}
            className="flex items-center gap-2 rounded-lg border border-fuchsia-500/40 bg-fuchsia-500/10 px-3 py-1.5 text-xs font-medium text-fuchsia-300 transition hover:bg-fuchsia-500/20 disabled:opacity-50"
          >
            {(busy || generateMutation.isPending) && <Spinner size="sm" />}
            {latest ? 'Regenerate analysis' : 'Analyze this run'}
          </button>
        )}
      </div>

      <div className="rounded-lg border border-fuchsia-500/20 bg-slate-800/60 p-5">
        {isLoading && (
          <div className="flex items-center justify-center py-8">
            <Spinner size="lg" />
          </div>
        )}

        {!isLoading && !latest && (
          <p className="py-4 text-center text-sm text-slate-500">
            {pipelineFinished
              ? 'No AI analysis yet. Click "Analyze this run" to have Claude review the training code, metrics, and history.'
              : 'The AI advisor will analyze this run automatically once the pipeline finishes.'}
          </p>
        )}

        {generateMutation.isError && (
          <div className="mb-4 rounded-lg border border-red-800 bg-red-900/20 px-4 py-3 text-sm text-red-300">
            {(generateMutation.error as Error).message}
          </div>
        )}

        {latest && busy && (
          <div className="flex items-center gap-3 py-6 text-sm text-slate-400">
            <Spinner size="sm" />
            Claude is reviewing the notebook code and metrics... this usually takes under a minute.
          </div>
        )}

        {latest?.status === 'failed' && (
          <div className="rounded-lg border border-red-800 bg-red-900/20 px-4 py-3 text-sm text-red-300">
            Analysis failed: {latest.error || 'unknown error'}
          </div>
        )}

        {latest?.status === 'ready' && (
          <div>
            <Markdown content={latest.content} />
            <p className="mt-5 border-t border-slate-700/60 pt-3 text-xs text-slate-500">
              Generated by <span className="text-slate-400">{latest.model}</span> ·{' '}
              {formatDate(latest.finished_at)}
            </p>
          </div>
        )}
      </div>
    </section>
  );
}

function SparklesIcon() {
  return (
    <svg className="h-4 w-4 text-fuchsia-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.29 6.86L21 12l-5.71 2.14L13 21l-2.29-6.86L5 12l5.71-2.14L13 3z" />
    </svg>
  );
}
